import React,{useEffect,useMemo,useState} from "react";
import {Search,Plus,Trash2,GripVertical,RefreshCcw,BookOpen,BarChart3,GitCompare,Landmark,Bell,ChevronRight,X,Zap,CheckCircle2} from "lucide-react";
import {ResponsiveContainer,LineChart,Line,XAxis,YAxis,Tooltip,CartesianGrid,ScatterChart,Scatter,ReferenceLine} from "recharts";

type Sec={id:string;symbol:string;name:string;exchange:string;assetType:string;price:number;bid:number;ask:number;volume:number;attention:any;history?:any[];returns?:any;spread?:number;spreadBps?:number};
const API_BASE=(import.meta.env.VITE_API_URL||"").replace(/\/$/,"");
const api=async(path:string,opts?:RequestInit)=>{const r=await fetch(`${API_BASE}${path}`,opts);if(!r.ok)throw Error("API error");return r.status===204?null:r.json()};
const pct=(n:number)=>`${n>=0?"+":""}${n.toFixed(2)}%`;
const money=(n:number,type?:string)=>type==="GSEC"?`${n.toFixed(2)}%`:`₹${n.toLocaleString("en-IN",{maximumFractionDigits:2})}`;

export default function App(){
 const [items,setItems]=useState<Sec[]>([]),[changes,setChanges]=useState<any[]>([]),[search,setSearch]=useState(""),[selected,setSelected]=useState<Sec|null>(null),[view,setView]=useState("Overview"),[compare,setCompare]=useState<string[]>([]),[toast,setToast]=useState(""),[rrg,setRrg]=useState<any[]>([]),[fixed,setFixed]=useState<any>(null),[method,setMethod]=useState(false);
 const load=async()=>{const w=await api("/api/watchlists");setItems(w.items);setChanges(w.changes);};
 useEffect(()=>{load();api("/api/rrg").then(setRrg);api("/api/fixed-income").then(setFixed)},[]);
 useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(""),2600);return()=>clearTimeout(t)}},[toast]);
 const filtered=useMemo(()=>items.filter(x=>x.symbol.toLowerCase().includes(search.toLowerCase())||x.name.toLowerCase().includes(search.toLowerCase())),[items,search]);
 const [results,setResults]=useState<Sec[]>([]);
 useEffect(()=>{if(!search.trim()){setResults([]);return;} const t=setTimeout(()=>api(`/api/securities?q=${encodeURIComponent(search)}`).then(setResults).catch(()=>setResults([])),180);return()=>clearTimeout(t)},[search]);
 const sim=async()=>{await api("/api/demo/simulate",{method:"POST"});await load();setToast("Demo market movement applied");};
 const reset=async()=>{await api("/api/demo/reset",{method:"POST"});await load();setToast("Demo reset");};
 const reviewed=async()=>{await api("/api/watchlists/w1/snapshot",{method:"POST"});await load();setToast("Snapshot saved — you're up to date");};
 const add=async(id:string)=>{await api("/api/watchlists/w1/items",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({securityId:id})});await load();setSearch("")};
 const remove=async(id:string)=>{await api(`/api/watchlists/w1/items/${id}`,{method:"DELETE"});await load()};
 const detail=async(id:string)=>setSelected(await api(`/api/securities/${id}`));
 return <div className="app">
  <header className="top"><div className="brand">FIN<span>TRACE</span><small>MARKET INTELLIGENCE</small></div>
   <div className="search"><Search size={17}/><input placeholder="Search securities..." value={search} onChange={e=>setSearch(e.target.value)}/>{search&&<div className="results">{results.length?results.slice(0,7).map(x=><button key={x.id} onClick={()=>add(x.id)}><b>{x.symbol}</b><span>{x.name} · {x.exchange}</span><Plus size={16}/></button>):<span className="empty">No matches</span>}</div>}</div>
   <div className="status"><i/> DEMO DATA <span>•</span> {new Date().toLocaleTimeString("en-IN",{hour:"2-digit",minute:"2-digit"})} IST</div>
  </header>
  <nav>{["Overview","Watchlists","Markets","Fixed Income","Alerts"].map(x=><button className={view===x?"active":""} onClick={()=>setView(x)} key={x}>{x}</button>)}<button className="method" onClick={()=>setMethod(true)}><BookOpen size={15}/> Methodology</button></nav>
  <main>
   <div className="hero"><div><div className="eyebrow">YOUR MARKET, WITH A MEMORY</div><h1>My Market</h1><p>Track the market. Trace what changed. Know what matters.</p></div>
    <div className="actions"><button className="secondary" onClick={reviewed}><CheckCircle2 size={16}/> Mark reviewed</button><button className="secondary" onClick={sim}><Zap size={16}/> Simulate market movement</button><button className="iconbtn" title="Reset demo" onClick={reset}><RefreshCcw size={17}/></button></div>
   </div>
   {view==="Overview"||view==="Watchlists"?<>
   <section className="memory">
    <div className="section-head"><div><div className="eyebrow">SINCE YOU LAST CHECKED</div><h2>{changes.length?`Welcome back — ${changes.length} meaningful ${changes.length===1?"change":"changes"}`:"Everything is up to date"}</h2></div><button className="textbtn">View all <ChevronRight size={15}/></button></div>
    {changes.length?<div className="change-grid">{changes.slice(0,4).map((x:any)=><button className="change" key={x.id} onClick={()=>detail(x.id)}><div><b>{x.symbol}</b><span className={`level ${x.change.level.toLowerCase()}`}>{x.change.level}</span></div><strong>{pct(x.change.priceChange)}</strong><small>{x.change.relative>=0?"+":""}{x.change.relative.toFixed(2)}pp vs NIFTY · {x.change.volumeRatio.toFixed(1)}× volume</small></button>)}</div>:<div className="empty-state"><CheckCircle2/> <div><b>Everything is up to date.</b><span>Mark this watchlist reviewed, then simulate a movement to experience FINTRACE's memory.</span></div></div>}
   </section>
   <section className="table-panel"><div className="section-head"><div><div className="eyebrow">WATCHLIST</div><h2>My Market <span className="count">{items.length} securities</span></h2></div><button className="secondary" onClick={()=>setView("Compare")}><GitCompare size={15}/> Compare</button></div>
    <div className="table-wrap"><table><thead><tr><th></th><th>Symbol</th><th>Price</th><th>1D</th><th>5D</th><th>1M</th><th>1Y</th><th>Volume</th><th>Bid</th><th>Ask</th><th>Spread</th><th>Attention</th><th></th></tr></thead><tbody>{filtered.map(x=><tr key={x.id} onClick={()=>detail(x.id)}><td className="drag"><GripVertical size={15}/></td><td><b>{x.symbol}</b><small>{x.name}</small></td><td className="num">{money(x.price,x.assetType)}</td><td className={x.attention.priceChange>=0?"pos":"neg"}>{pct(x.attention.priceChange)}</td><td className="muted">{pct(x.attention.priceChange*.62)}</td><td className="muted">{pct(x.attention.priceChange*1.9)}</td><td className="muted">{pct(x.attention.priceChange*4.7)}</td><td>{x.volume?`${(x.volume/1000000).toFixed(2)}M`:"—"}</td><td>{money(x.bid,x.assetType)}</td><td>{money(x.ask,x.assetType)}</td><td>{x.spread!=null?x.spread.toFixed(2):"—"}</td><td><span className={`score ${x.attention.level?.toLowerCase()}`}>{x.attention.score}</span></td><td><button className="rowdel" onClick={e=>{e.stopPropagation();remove(x.id)}}><Trash2 size={14}/></button></td></tr>)}</tbody></table></div>
   </section>
   <div className="lower"><section className="panel"><div className="eyebrow">ATTENTION LEADERS</div><h2>Where to look next</h2>{[...items].sort((a,b)=>(b.attention.score||0)-(a.attention.score||0)).slice(0,4).map(x=><button className="leader" key={x.id} onClick={()=>detail(x.id)}><span><b>{x.symbol}</b><small>{x.attention.level||"LOW"}</small></span><strong>{x.attention.score}</strong></button>)}</section><section className="panel"><div className="eyebrow">MARKET MEMORY</div><h2>What FINTRACE measures</h2><div className="metric"><BarChart3/><span>Price + relative performance</span><b>60%</b></div><div className="metric"><RefreshCcw/><span>Volume anomaly</span><b>20%</b></div><div className="metric"><Bell/><span>Volatility + microstructure</span><b>20%</b></div></section></div>
   </>:view==="Compare"?<Compare items={items} selected={compare} setSelected={setCompare}/>:view==="Fixed Income"?<Fixed fixed={fixed}/>:view==="Markets"?<RRG data={rrg}/>:<Alerts/>}
  </main>
  {selected&&<Detail sec={selected} close={()=>setSelected(null)}/>}
  {method&&<Method close={()=>setMethod(false)}/>}
  {toast&&<div className="toast">{toast}</div>}
 </div>
}

function Detail({sec,close}:{sec:Sec;close:()=>void}){
 const [history,setHistory]=useState<any[]>([]); useEffect(()=>{api(`/api/securities/${sec.id}/history`).then(setHistory)},[sec.id]);
 const data=history.slice(-80).map((x,i)=>({...x,label:i}));
 return <div className="overlay"><aside className="drawer"><button className="close" onClick={close}><X/></button><div className="eyebrow">SECURITY DETAIL · {sec.exchange}</div><h1>{sec.symbol}</h1><p className="name">{sec.name}</p><div className="quote"><strong>{money(sec.price,sec.assetType)}</strong><span className={sec.attention?.priceChange>=0?"pos":"neg"}>{pct(sec.attention?.priceChange||0)}</span></div><div className="quote-grid"><div>Bid<b>{money(sec.bid,sec.assetType)}</b></div><div>Ask<b>{money(sec.ask,sec.assetType)}</b></div><div>Spread<b>{sec.spread?.toFixed(2)??"—"}</b></div><div>Spread BPS<b>{sec.spreadBps?.toFixed(1)??"—"}</b></div></div><div className="chartbox"><div className="charttitle"><b>Price history</b><span>1Y</span></div><ResponsiveContainer width="100%" height={230}><LineChart data={data}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="label" hide/><YAxis domain={["auto","auto"]} tickFormatter={v=>String(Math.round(v))}/><Tooltip labelFormatter={()=>""} formatter={(v:any)=>[Number(v).toFixed(2),"Price"]}/><Line type="monotone" dataKey="close" dot={false} strokeWidth={2}/></LineChart></ResponsiveContainer></div><div className="why"><div className="eyebrow">WHY IT MATTERS</div><p>{sec.attention?.why||"No snapshot exists yet. Mark the watchlist reviewed to establish a baseline."}</p><div className="attention-big"><span>Attention score</span><b>{sec.attention?.score??0}</b><em>{sec.attention?.level??"LOW"}</em></div><small>No verified market event detected from available data. FINTRACE never fabricates a reason.</small></div></aside></div>
}
function Compare({items,selected,setSelected}:{items:Sec[];selected:string[];setSelected:React.Dispatch<React.SetStateAction<string[]>>}){const data=Array.from({length:60},(_,i)=>{const o:any={i};items.filter(x=>selected.includes(x.id)).forEach((x,j)=>o[x.symbol]=100+(x.attention.priceChange||0)*(i/59)*1.8);return o});return <section className="page"><div className="eyebrow">MULTI-SECURITY COMPARISON</div><h1>Relative performance</h1><p>Select securities and normalize them to 100 at the start.</p><div className="chips">{items.slice(0,10).map(x=><button className={selected.includes(x.id)?"chip on":"chip"} onClick={()=>setSelected(s=>s.includes(x.id)?s.filter(id=>id!==x.id):[...s,x.id])} key={x.id}>{x.symbol}</button>)}</div><div className="bigchart"><ResponsiveContainer width="100%" height={430}><LineChart data={data}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="i"/><YAxis/><Tooltip/><LegendProxy names={selected.map(id=>items.find(x=>x.id===id)?.symbol||"")}/>{selected.map(id=><Line key={id} type="monotone" dataKey={items.find(x=>x.id===id)?.symbol} dot={false} strokeWidth={2}/>)}</LineChart></ResponsiveContainer></div></section>}
function LegendProxy({names}:{names:string[]}){return <div className="legend">{names.map(n=><span key={n}>● {n}</span>)}</div>}
function RRG({data}:{data:any[]}){return <section className="page"><div className="eyebrow">RELATIVE ROTATION GRAPH</div><h1>Strength vs momentum</h1><p>Benchmark: NIFTY 50 · descriptive, not predictive.</p><div className="rrg"><ResponsiveContainer width="100%" height={500}><ScatterChart margin={{top:30,right:30,bottom:30,left:30}}><CartesianGrid/><XAxis type="number" dataKey="x" domain={[94,106]} name="Relative strength"/><YAxis type="number" dataKey="y" domain={[94,106]} name="Momentum"/><ReferenceLine x={100}/><ReferenceLine y={100}/><Tooltip cursor={{strokeDasharray:"3 3"}} content={({payload}:any)=>(payload?.[0]?<div className="tip"><b>{payload[0].payload.symbol}</b><br/>RS {payload[0].payload.x.toFixed(1)} · Momentum {payload[0].payload.y.toFixed(1)}<br/>{payload[0].payload.quadrant}</div>:null)}/><Scatter data={data}/></ScatterChart></ResponsiveContainer><div className="quad q1">LEADING</div><div className="quad q2">WEAKENING</div><div className="quad q3">IMPROVING</div><div className="quad q4">LAGGING</div></div></section>}
function Fixed({fixed}:{fixed:any}){if(!fixed)return null;const d=[{name:"5Y",yield:fixed.five.price},{name:"10Y",yield:fixed.ten.price}];return <section className="page"><div className="eyebrow">FIXED INCOME</div><h1>Government securities</h1><p>Rates are shown as demo observations, clearly labeled.</p><div className="fixedcards"><div><span>GSEC 5Y</span><b>{fixed.five.price.toFixed(2)}%</b></div><div><span>GSEC 10Y</span><b>{fixed.ten.price.toFixed(2)}%</b></div><div><span>10Y–5Y</span><b>+{fixed.spread.toFixed(0)} bps</b></div></div><div className="bigchart"><ResponsiveContainer width="100%" height={350}><LineChart data={d}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="name"/><YAxis domain={["auto","auto"]}/><Tooltip/><Line type="monotone" dataKey="yield" strokeWidth={3}/></LineChart></ResponsiveContainer></div></section>}
function Alerts(){return <section className="page"><div className="eyebrow">ALERTS</div><h1>Simple in-app alerts</h1><p>Demo alert infrastructure is intentionally lightweight.</p><div className="alertrow"><Bell/><div><b>RELIANCE &gt; ₹1500</b><span>Condition · Ready</span></div><em>ACTIVE</em></div><div className="alertrow"><Bell/><div><b>1D return &gt; 3%</b><span>Condition · Ready</span></div><em>ACTIVE</em></div><div className="alertrow"><Landmark/><div><b>GSEC 10Y moves &gt; 5 bps</b><span>Condition · Ready</span></div><em>ACTIVE</em></div></section>}
function Method({close}:{close:()=>void}){return <div className="overlay"><aside className="methoddrawer"><button className="close" onClick={close}><X/></button><div className="eyebrow">METHODOLOGY</div><h1>Explainable by design.</h1><p>Every score is derived from observable market state. The explanation layer uses structured facts only.</p>{[["Returns","(Current / Starting − 1) × 100"],["Spread","Ask − Bid"],["Spread BPS","((Ask − Bid) / Mid) × 10000"],["Relative performance","Security return − NIFTY return"],["Attention","35% price · 25% relative · 20% volume · 10% volatility · 10% spread/yield"],["RRG","Relative strength = Security / NIFTY; momentum is derived from its series"]].map(([a,b])=><div className="formula" key={a}><b>{a}</b><code>{b}</code></div>)}<div className="note">Attention is an investigation aid, not a prediction or buy/sell signal.</div></aside></div>}
